<?xml version="1.0"?>
<!--
  Robot model adapted from https://github.com/CIR-KIT/steer_drive_ros/blob/kinetic-devel/steer_drive_controller/test/common/urdf/steerbot.xacro

  Modifications:
    Remove base_footprint link. Useful for navigation but not necessary for a simple example.
    Added materials for URDF
    Updated inertials

  Geometry:
    The Ackermann steering controllers require the longitudinal
    separation between the front and back wheel axes and the
    lateral separation between the left and right front steering axes.
    
    For this model:
    wheel_separation_h = base_length - 2 * axle_offset = 0.4
    wheel_separation_w = base_width  + 2 * axle_offset = 0.4
-->
<robot name="erp42_vehicle" xmlns:xacro="http://wiki.ros.org/xacro">
  <!-- Include xacro for inertials, materials and wheels -->
  <xacro:include filename="$(find erp42_vehicle_description)/urdf/wheel.xacro"/>
  <!-- <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/> -->
  <!-- <xacro:include filename="$(find livox_laser_simulation)/urdf/livox_horizon.xacro"/> -->
  

  <xacro:property name="robot_namespace" value="/erp42_vehicle"/>

  <!-- Gazebo plugins -->
  <gazebo>
    <!-- Load ros_control plugin using the steer_bot_hardware_gazebo
    implementation of the hardware_interface::RobotHW -->
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <!-- <robotNamespace>${robot_namespace}</robotNamespace> -->
      <robotSimType>erp42_hardware_gazebo/ERP42HardwareGazebo</robotSimType>
      <legacyModeNS>false</legacyModeNS>
    </plugin>
  </gazebo>



  <!-- Math constants -->
  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>

  <!-- Robot base dimensions -->
  <xacro:property name="base_length" value="1.3317" />
  <xacro:property name="base_width" value="0.78" />
  <xacro:property name="base_height" value="0.2" />
  <xacro:property name="base_mass" value="200" />

  <!-- Nose link dimensions -->
  <xacro:property name="nose_length" value="0.5078" />
  <xacro:property name="nose_width" value="0.34" />
  <xacro:property name="nose_height" value="0.2" />
  <xacro:property name="nose_mass" value="1" />

  <!-- Wheel link dimensions -->
  <xacro:property name="front_wheel_radius" value="0.2578" />
  <xacro:property name="rear_wheel_radius" value="0.2705" />
  <xacro:property name="wheel_thickness" value="0.08" />
  <xacro:property name="wheel_mass" value="1" />

  <!-- Steering link dimensions -->
  <xacro:property name="steer_radius" value="0.05" />
  <xacro:property name="steer_thickness" value="0.02" />
  <xacro:property name="steer_mass" value="1" />

  <!-- Axle positions 0.6609-->
  <xacro:property name="axle_offset" value="0.05" />
  <xacro:property name="steer_offset" value="0.02" />
  <xacro:property name="wheel_offset" value="0.05" />
  <xacro:property name="origin_offset" value="${base_length/2-wheel_offset}" />

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="${origin_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="${origin_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:solid_cuboid_inertial
        rpy="0 0 0" xyz="${origin_offset} 0 0"
        mass="${base_mass}"
        x="${base_length}" y="${base_width}" z="${base_height}" />
  </link>

  <!-- Nose link -->
  <joint name="nose_joint" type="fixed">
    <axis xyz="1 0 0" />
    <origin xyz="${base_length/2+nose_length/2+origin_offset} 0 0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="nose_link"/>
   </joint>
  <link name="nose_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${nose_length} ${nose_width} ${nose_height}"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${nose_length} ${nose_width} ${nose_height}"/>
      </geometry>
    </collision>
    <xacro:solid_cuboid_inertial
        rpy="0 0 0" xyz="0 0 0"
        mass="${nose_mass}"
        x="${nose_length}" y="${nose_width}" z="${nose_height}" />
  </link>

  <!-- Front steer and rear wheel joints required for ackermann_steering_controller -->
  <xacro:front_steer
    name="front"
    parent="base"
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}"
    steer_mass="${steer_mass}"
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${front_wheel_radius+steer_offset}"
    origin_offset="${origin_offset}">
  </xacro:front_steer>

  <xacro:rear_wheel
    name="rear"
    parent="base"
    wheel_radius="${rear_wheel_radius/4}"
    wheel_thickness="${wheel_thickness/2}"
    wheel_mass="${wheel_mass/32}">
    <origin xyz="${-base_length/2+wheel_offset+origin_offset} 0 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel>

  <!-- Steerable front wheels -->
  <xacro:front_wheel_lr
    name="front_right"
    parent="base"
    reflect="-1"
    wheel_radius="${front_wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}"
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}"
    steer_mass="${steer_mass}"
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${front_wheel_radius+steer_offset}"
    origin_offset="${origin_offset}">
  </xacro:front_wheel_lr>
  <xacro:front_wheel_lr
    name="front_left"
    parent="base"
    reflect="1"
    wheel_radius="${front_wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}"
    steer_radius="${steer_radius}"
    steer_thickness="${steer_thickness}"
    steer_mass="${steer_mass}"
    base_length="${base_length}"
    base_width="${base_width}"
    axle_offset="${axle_offset}"
    steer_height="${front_wheel_radius+steer_offset}"
    origin_offset="${origin_offset}">
  </xacro:front_wheel_lr>

  <!-- Rear wheels -->
  <xacro:rear_wheel_lr
    name="rear_right"
    parent="base"
    wheel_radius="${rear_wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}">
    <origin xyz="${-base_length/2+wheel_offset+origin_offset} ${-base_width/2-axle_offset} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>
  <xacro:rear_wheel_lr
    name="rear_left"
    parent="base"
    wheel_radius="${rear_wheel_radius}"
    wheel_thickness="${wheel_thickness}"
    wheel_mass="${wheel_mass}">
    <origin xyz="${-base_length/2+wheel_offset+origin_offset} ${+base_width/2+axle_offset} 0" rpy="${-90 * deg_to_rad} 0 0"/>
  </xacro:rear_wheel_lr>

  <!-- Colour -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- VLP-16 -->
  <!-- <VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points" hz="50" samples="1024" gpu="true" lasers="16" max_range="100">
    <origin xyz="${origin_offset-0.2317} 0 0.5515" rpy="0 0 0" />
  </VLP-16> -->

  <!-- LIVOX -->
  <!-- <Livox_Horizon parent="base_link" name="livox" visualize="false" publish_pointcloud_type="3" downsample="1">
    <origin xyz="${origin_offset} 0 0.5" rpy="0 0 0" />
  </Livox_Horizon> -->

    <!-- IMU link -->
   <joint name="imu_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="${origin_offset-0.2317} 0 0.7015" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="imu_link"/>
   </joint>
   <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.02"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.02"/>
      </geometry>
    </collision>
   </link>

    <!-- GPS link -->
  <joint name="gps_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="${origin_offset-0.5317} 0 0.5015" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="gps_link"/>
  </joint>
  <link name="gps_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.02"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.02"/>
      </geometry>
    </collision>
  </link>

  <!-- Camera Joint -->
  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${origin_offset-0.763} 0 0.145" rpy="0 ${30 * deg_to_rad} ${180 * deg_to_rad}"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera Object -->
  <xacro:property name="camera_size" value="0.05" /> <!-- Size of square 'camera' box -->
  <link name="camera_link">
    <collision>
        <geometry>
            <box size=".1 .3 .1"/>
        </geometry>
        <contact_coefficients mu="0" kp="1000.0" kd="1.0"/>
    </collision>

    <visual>
        <geometry>
            <mesh filename="package://erp42_vehicle_description/meshes/sensors/kinect.dae"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 1.57"/>
        <material name="black"/>
    </visual>

    <inertial>
        <mass value="8.1"/>
        <inertia ixx="0.0675" ixy="0.0" ixz="0.0"
                 iyy="0.0135" iyz="0.0"
                 izz="0.0675"/>
    </inertial>
    </link>

  <!-- Camera Plugin -->
  <!-- <gazebo reference="camera_link">
    <material>Gazebo/Black</material>
    <sensor type="depth" name="camera_ir">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>600</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.07</stddev>
        </noise>

      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>10.0</updateRate>
        <cameraName>camera_ir</cameraName>
        <imageTopicName>/camera/color/image_raw</imageTopicName>
        <cameraInfoTopicName>/camera/color/camera_info</cameraInfoTopicName>
        <depthImageTopicName>/camera/depth/image_raw</depthImageTopicName>
        <depthImageCameraInfoTopicName>/camera/depth/camera_info</depthImageCameraInfoTopicName>
        <pointCloudTopicName>/camera/depth/points</pointCloudTopicName>
        <frameName>camera_link</frameName>
        <pointCloudCutoff>0.4</pointCloudCutoff>
        <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
        <CxPrime>0</CxPrime>
        <Cx>0</Cx>
        <Cy>0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0.07</hackBaseline>
      </plugin>
    </sensor>
  </gazebo> -->

  <gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>imu_link</bodyName>
      <topicName>imu</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>20.0</updateRate>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gps_plugin" filename="libhector_gazebo_ros_gps.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>gps_link</bodyName>
      <topicName>fix</topicName>
      <velocitytopicName>fixvelocity</velocitytopicName>
      <drift>0.0 0.0 0.0</drift>
      <gaussianNoise>0 0 0</gaussianNoise>
      <velocitydrift>0 0 0</velocitydrift>
      <velocitygaussianNoise>0 0 0</velocitygaussianNoise>
      <updateRate>10.0</updateRate>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_p3d" filename="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>30.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>ground_truth_pose</topicName>
      <gaussianNoise>0.0</gaussianNoise>
      <frameName>map</frameName>
    </plugin>
  </gazebo>

</robot>
